main: com.teunjojo.SimpleAutoRestart
name: ${project.name}
version: ${project.version}
description: ${project.description}
api-version: 1.19
author: teunjojo
website: ${project.url}
folia-supported: true